/** Maillage interne SEO — liens contextuels par page publique. */

export type SeoInternalLink = { href: string; label: string };

export const SEO_INTERNAL_LINKS: Record<string, SeoInternalLink[]> = {
  "/": [
    { href: "/#plateforme", label: "Socle plateforme BeWork" },
    { href: "/#marches", label: "Analyse des marchés" },
    { href: "/#outils-ia", label: "Outils IA spécialisés BTP" },
    { href: "/#confidentialite", label: "Confidentialité et données" },
    { href: "/#tarifs", label: "Tarification sur étude" },
    { href: "/#partenaire", label: "Partenaire technologique" },
    { href: "/reponse-appel-offres-btp", label: "Réponse appels d'offres BTP" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE BTP" },
    { href: "/services/doe-btp", label: "Suivi DOE BTP" },
    { href: "/ressources/memoire-technique-btp", label: "Mémoire technique BTP" },
    { href: "/tarifs", label: "Méthode de tarification" },
    { href: "/ressources", label: "Guides et tutoriels BTP" },
    { href: "/contact", label: "Demander une démonstration" },
    { href: "/notre-facon-de-travailler", label: "Notre façon de travailler" },
  ],
  "/tarifs": [
    { href: "/#plateforme", label: "Découvrir la plateforme" },
    { href: "/#partenaire", label: "Partenaire technologique" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE BTP" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/notre-facon-de-travailler", label: "Méthode et validation" },
    { href: "/faq", label: "FAQ" },
    { href: "/contact", label: "Demander une étude" },
  ],
  "/contact": [
    { href: "/tarifs", label: "Tarifs assistant travaux BTP" },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Exécution marché public",
    },
    { href: "/reponse-appel-offres-btp", label: "Réponse appels d'offres" },
    { href: "/notre-facon-de-travailler", label: "Notre méthode" },
    { href: "/services", label: "Services BeWork" },
    { href: "/faq", label: "FAQ" },
  ],
  "/faq": [
    { href: "/notre-facon-de-travailler", label: "Méthode et validation" },
    { href: "/tarifs", label: "Tarifs" },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Exécution marché public (7 blocs)",
    },
    {
      href: "/assistants-administratifs-taches#reponses-appels-offres",
      label: "Réponses appels d'offres",
    },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/contact", label: "Contacter BeWork" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
  ],
  "/services": [
    { href: "/promoteurs-immobiliers", label: "Promoteurs immobiliers" },
    { href: "/services/assistant-travaux", label: "Assistant travaux BTP" },
    { href: "/services/compte-rendu-chantier", label: "Comptes rendus chantier" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/services/doe-btp", label: "DOE BTP" },
    { href: "/ressources", label: "Ressources et guides" },
  ],
  "/externaliser-administratif": [
    { href: "/services/externalisation-administrative-btp", label: "Externalisation administrative BTP" },
    { href: "/assistants-administratifs-taches", label: "Missions déléguables" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/admin-btp-sans-recruter", label: "Admin BTP sans recruter" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Contact" },
  ],
  "/assistant-administratif-externalise": [
    { href: "/externaliser-administratif", label: "Externaliser l'administratif" },
    { href: "/assistants-administratifs-taches", label: "Catalogue missions" },
    { href: "/services/assistant-travaux", label: "Assistant travaux IA" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-administratif-pme": [
    { href: "/assistant-administratif-externalise", label: "Assistant externalisé" },
    { href: "/assistants-administratifs-taches", label: "Missions BTP" },
    { href: "/admin-btp-sans-recruter", label: "Admin sans recruter" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-administratif-distance": [
    { href: "/assistant-travaux-france", label: "Assistant travaux France" },
    { href: "/assistants-administratifs-taches", label: "Missions déléguables" },
    { href: "/externalisation-administrative-btp-france", label: "Externalisation France" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/avenant-chantier": [
    { href: "/devis-retard-btp", label: "Devis en retard" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/assistants-administratifs-taches", label: "Missions assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/suivi-fournisseurs-chantier": [
    { href: "/assistants-administratifs-taches", label: "Missions logistique & fournisseurs" },
    { href: "/dict-dt-travaux", label: "DICT & DT travaux" },
    { href: "/chantier-mal-suivi", label: "Chantier mal suivi" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/admin-btp-sans-recruter": [
    { href: "/comparatif-assistance-travaux-btp", label: "Comparatif recruter / BeWork" },
    { href: "/assistants-administratifs-taches", label: "Missions déléguables" },
    { href: "/externaliser-administratif", label: "Externaliser l'administratif" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Contact" },
  ],
  "/blog": [
    { href: "/reponse-appel-offres-btp", label: "Réponse appels d'offres BTP" },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Exécution marché public",
    },
    { href: "/ressources/analyse-dce-btp", label: "Guide analyse DCE" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/notre-facon-de-travailler": [
    { href: "/tarifs", label: "Tarifs assistant travaux BTP" },
    { href: "/assistants-administratifs-taches", label: "Missions déléguables" },
    { href: "/promoteurs-immobiliers", label: "Promoteurs immobiliers" },
    { href: "/services", label: "Tous les services" },
    { href: "/contact", label: "Démarrer un échange" },
    { href: "/faq", label: "FAQ" },
  ],
  "/assistant-travaux-lyon": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-paris", label: "Paris" },
    { href: "/assistant-travaux-marseille", label: "Marseille" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres BTP" },
    { href: "/assistants-administratifs-taches#marches-publics-accords-cadres", label: "Marchés publics" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-marseille": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-lyon", label: "Lyon" },
    { href: "/assistant-travaux-toulouse", label: "Toulouse" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-lille": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-paris", label: "Paris" },
    { href: "/assistant-travaux-belgique", label: "Belgique" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-bordeaux": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-toulouse", label: "Toulouse" },
    { href: "/assistant-travaux-paris", label: "Paris" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-toulouse": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-bordeaux", label: "Bordeaux" },
    { href: "/assistant-travaux-marseille", label: "Marseille" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-bruxelles": [
    { href: "/assistant-travaux-belgique", label: "Belgique" },
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-geneve", label: "Genève" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-geneve": [
    { href: "/assistant-travaux-suisse", label: "Suisse" },
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-bruxelles", label: "Bruxelles" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/cas-clients": [
    { href: "/comparatif-assistance-travaux-btp", label: "Recruter ou BeWork ?" },
    { href: "/cas-clients/ccmi-martin-audit-devis", label: "Audit devis CCMI Martin" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Démarrer un échange" },
  ],
  "/assistants-administratifs-taches": [
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Exécution marché public (7 blocs)",
    },
    {
      href: "/assistants-administratifs-taches#reponses-appels-offres",
      label: "Réponses appels d'offres & DCE",
    },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/facturation-chorus-pro-btp", label: "Chorus Pro BTP" },
    { href: "/reponse-appel-offres-btp", label: "Landing appels d'offres" },
    { href: "/services/assistant-travaux", label: "Assistant travaux IA" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Parler de mon marché" },
  ],
  "/relance-devis-btp": [
    { href: "/blog/relancer-devis-btp-sans-perdre-client", label: "Relancer un devis sans perdre le client" },
    { href: "/ressources/chiffrage-devis-btp", label: "Chiffrage devis BTP" },
    { href: "/devis-retard-btp", label: "Devis en retard" },
    { href: "/tarifs", label: "Tarifs BeWork" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
  ],
  "/devis-retard-btp": [
    { href: "/relance-devis-btp", label: "Relance devis BTP" },
    { href: "/ressources/chiffrage-devis-btp", label: "Méthode chiffrage devis" },
    { href: "/avenant-chantier", label: "Avenants chantier" },
    { href: "/tarifs", label: "Voir les tarifs" },
  ],
  "/chantier-mal-suivi": [
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu de chantier" },
    { href: "/ressources/doe-btp", label: "DOE BTP" },
    { href: "/admin-btp-sans-recruter", label: "Admin BTP sans recruter" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
  ],
  "/facture-impayee-btp": [
    { href: "/impayes-btp-relances", label: "Impayés et relances" },
    { href: "/situation-travaux-btp", label: "Situations de travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/ressources/ppsps-btp": [
    { href: "/ressources/doe-btp", label: "DOE BTP" },
    { href: "/services/ppsps", label: "Service PPSPS BeWork" },
    { href: "/ressources/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/assistants-administratifs-taches", label: "Documents chantier délégués" },
  ],
  "/ressources/doe-btp": [
    { href: "/ressources/ppsps-btp", label: "PPSPS BTP" },
    { href: "/ressources/pv-levee-reserves-btp", label: "Levée de réserves" },
    { href: "/services/doe-btp", label: "Accompagnement DOE" },
    { href: "/externaliser-administratif", label: "Externaliser l’administratif" },
  ],
  "/ressources/analyse-dce-btp": [
    { href: "/ressources/analyse-dce-chiffrage-btp", label: "Analyse DCE & appui chiffrage" },
    { href: "/ressources/memoire-technique-btp", label: "Mémoire technique" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE avec BeWork" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant chargé d’affaires" },
    { href: "/relance-devis-btp", label: "Relance devis" },
  ],
  "/ressources/analyse-dce-chiffrage-btp": [
    { href: "/ressources/analyse-dce-btp", label: "Guide analyse DCE" },
    { href: "/ressources/chiffrage-devis-btp", label: "Méthode chiffrage devis" },
    { href: "/devis-retard-btp", label: "Devis en retard" },
    { href: "/services/chiffrage-devis-btp", label: "Appui chiffrage BeWork" },
    { href: "/services/analyse-dce-btp", label: "Service analyse DCE" },
    { href: "/ressources", label: "Hub ressources" },
    { href: "/contact", label: "Contact" },
  ],
  "/ressources/compte-rendu-chantier": [
    { href: "/services/compte-rendu-chantier", label: "Comptes rendus avec BeWork" },
    { href: "/ressources/planning-chantier-btp", label: "Planning chantier" },
    { href: "/chantier-mal-suivi", label: "Chantier mal suivi" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/ressources/memoire-technique-btp": [
    { href: "/ressources/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/services/memoire-technique-btp", label: "Mémoire technique BeWork" },
    { href: "/ressources/chiffrage-devis-btp", label: "Chiffrage devis" },
  ],
  "/externalisation-administrative-btp-france": [
    { href: "/externalisation-administrative-btp-belgique", label: "Belgique" },
    { href: "/externalisation-administrative-btp-suisse", label: "Suisse" },
    { href: "/externalisation-administrative-btp-luxembourg", label: "Luxembourg" },
    { href: "/services/externalisation-administrative-btp", label: "Externalisation BTP" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/externalisation-administrative-btp-belgique": [
    { href: "/externalisation-administrative-btp-france", label: "France" },
    { href: "/externalisation-administrative-btp-suisse", label: "Suisse" },
    { href: "/externalisation-administrative-btp-luxembourg", label: "Luxembourg" },
    { href: "/services/externalisation-administrative-btp", label: "Externalisation BTP" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/externalisation-administrative-btp-suisse": [
    { href: "/externalisation-administrative-btp-france", label: "France" },
    { href: "/externalisation-administrative-btp-belgique", label: "Belgique" },
    { href: "/externalisation-administrative-btp-luxembourg", label: "Luxembourg" },
    { href: "/services/externalisation-administrative-btp", label: "Externalisation BTP" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/externalisation-administrative-btp-luxembourg": [
    { href: "/externalisation-administrative-btp-france", label: "France" },
    { href: "/externalisation-administrative-btp-belgique", label: "Belgique" },
    { href: "/externalisation-administrative-btp-suisse", label: "Suisse" },
    { href: "/services/externalisation-administrative-btp", label: "Externalisation BTP" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-administratif-btp": [
    { href: "/services/assistant-travaux", label: "Assistant travaux IA" },
    { href: "/assistants-administratifs-taches", label: "Catalogue missions" },
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu chantier" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/services/assistant-travaux": [
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
    { href: "/ressources", label: "Ressources BTP" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/faq", label: "FAQ BeWork" },
  ],
  "/ressources/chiffrage-devis-btp": [
    { href: "/ressources/analyse-dce-chiffrage-btp", label: "Analyse DCE & appui chiffrage" },
    { href: "/relance-devis-btp", label: "Relance devis BTP" },
    { href: "/devis-retard-btp", label: "Devis en retard" },
    { href: "/services/chiffrage-devis-btp", label: "Chiffrage devis avec BeWork" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/ressources/planning-chantier-btp": [
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu de chantier" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
    { href: "/chantier-mal-suivi", label: "Chantier mal suivi" },
  ],
  "/ressources/pv-levee-reserves-btp": [
    { href: "/ressources/doe-btp", label: "DOE BTP" },
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu chantier" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
  ],
  "/ressources/tuto-skill-ppsps-bework": [
    { href: "/ressources/ppsps-btp", label: "Guide PPSPS BTP" },
    { href: "/services/ppsps", label: "Service PPSPS BeWork" },
    { href: "/ressources/guide-cdt-bework", label: "Guide conducteur de travaux" },
  ],
  "/ressources/tuto-skill-diuo-bework": [
    { href: "/ressources/tuto-skill-doe-bework", label: "Skill DOE" },
    { href: "/ressources/tuto-skill-ppsps-bework", label: "Skill PPSPS" },
    { href: "/ressources/doe-btp", label: "Guide DOE BTP" },
  ],
  "/ressources/tuto-skill-analyse-dce-bework": [
    { href: "/ressources/analyse-dce-btp", label: "Guide analyse DCE" },
    { href: "/ressources/memoire-technique-btp", label: "Mémoire technique" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE BeWork" },
  ],
  "/ressources/tuto-skill-analyse-ccap-bework": [
    { href: "/ressources/tuto-skill-analyse-dce-bework", label: "Skill analyse de DCE" },
    { href: "/ressources/tuto-skill-analyse-express-cctp-bework", label: "Skill analyse express CCTP" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE BeWork" },
  ],
  "/ressources/tuto-skill-doe-bework": [
    { href: "/ressources/doe-btp", label: "Guide DOE BTP" },
    { href: "/services/doe-btp", label: "Service DOE BeWork" },
    { href: "/ressources/pv-levee-reserves-btp", label: "PV levée de réserves" },
  ],
  "/ressources/tuto-skill-memoire-technique-bework": [
    { href: "/ressources/memoire-technique-btp", label: "Guide mémoire technique" },
    { href: "/ressources/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/services/memoire-technique-btp", label: "Mémoire technique BeWork" },
  ],
  "/ressources/tuto-skill-chiffrage-devis-bework": [
    { href: "/ressources/chiffrage-devis-btp", label: "Chiffrage devis BTP" },
    { href: "/relance-devis-btp", label: "Relance devis BTP" },
    { href: "/services/chiffrage-devis-btp", label: "Chiffrage devis BeWork" },
  ],
  "/ressources/tuto-skill-pv-levee-reserves-bework": [
    { href: "/ressources/pv-levee-reserves-btp", label: "Guide PV levée de réserves" },
    { href: "/ressources/doe-btp", label: "DOE BTP" },
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu chantier" },
  ],
  "/ressources/tuto-skill-constat-retard-bework": [
    { href: "/devis-retard-btp", label: "Devis en retard" },
    { href: "/ressources/planning-chantier-btp", label: "Planning chantier" },
    { href: "/chantier-mal-suivi", label: "Chantier mal suivi" },
  ],
  "/ressources/guide-cdt-bework": [
    { href: "/ressources/guide-conducteur-de-travaux-ia-bework", label: "Guide conducteur de travaux IA" },
    { href: "/ressources/compte-rendu-chantier-guide-btp", label: "Guide CR chantier" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
  ],
  "/ressources/guide-conducteur-de-travaux-ia-bework": [
    { href: "/ressources/guide-cdt-bework", label: "Guide CDT — version condensée" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
    { href: "/ressources/tutos", label: "Tous les tutos skills" },
  ],
  "/ressources/compte-rendu-chantier-guide-btp": [
    { href: "/ressources/compte-rendu-chantier", label: "Méthode CR chantier" },
    { href: "/ressources/tuto-skill-pv-levee-reserves-bework", label: "PV levée de réserves" },
    { href: "/services/compte-rendu-chantier", label: "CR chantier BeWork" },
  ],
  "/impayes-btp-relances": [
    { href: "/facture-impayee-btp", label: "Facture impayée BTP" },
    { href: "/situation-travaux-btp", label: "Situations de travaux" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Démarrer un échange" },
  ],
  "/situation-travaux-btp": [
    { href: "/blog/situation-travaux-marche-public-btp", label: "Situation travaux marché public" },
    { href: "/impayes-btp-relances", label: "Impayés et relances" },
    { href: "/facturation-chorus-pro-btp", label: "Facturation Chorus Pro" },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Situations marché public",
    },
    { href: "/facture-impayee-btp", label: "Facture impayée BTP" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
  ],
  "/reponse-appel-offres-btp": [
    { href: "/checklist-depot-appel-offres-btp", label: "Checklist dépôt AO BTP" },
    { href: "/blog/comment-repondre-appel-offres-btp", label: "Guide réponse AO BTP" },
    { href: "/blog/eviter-rejet-offre-marche-public", label: "Éviter le rejet d'offre" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE BTP" },
    { href: "/services/memoire-technique-btp", label: "Mémoire technique" },
    {
      href: "/assistants-administratifs-taches#reponses-appels-offres",
      label: "Section AO sur page missions",
    },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Exécution marché public (7 blocs)",
    },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Envoyer un DCE" },
    { href: "/faq", label: "FAQ appels d'offres" },
  ],
  "/facturation-chorus-pro-btp": [
    { href: "/blog/chorus-pro-facture-refusee-que-faire", label: "Facture Chorus Pro refusée" },
    { href: "/blog/chorus-pro-entreprises-btp", label: "Guide Chorus Pro BTP" },
    { href: "/situation-travaux-btp", label: "Situations de travaux" },
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Situations & Chorus Pro (7 blocs)",
    },
    { href: "/gestion-marche-public-btp", label: "Gestion marché public" },
    { href: "/impayes-btp-relances", label: "Relances impayés" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Contact" },
  ],
  "/gestion-marche-public-btp": [
    {
      href: "/assistants-administratifs-taches#marches-publics-accords-cadres",
      label: "Détail exécution marché (7 blocs)",
    },
    {
      href: "/assistants-administratifs-taches#reponses-appels-offres",
      label: "Réponses appels d'offres",
    },
    { href: "/reponse-appel-offres-btp", label: "Landing appels d'offres" },
    { href: "/facturation-chorus-pro-btp", label: "Chorus Pro BTP" },
    { href: "/services/doe-btp", label: "DOE BTP" },
    { href: "/services/externalisation-administrative-btp", label: "Externalisation administrative" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Confier un dossier" },
  ],
  "/promoteurs-immobiliers": [
    { href: "/assistants-administratifs-taches", label: "Catalogue des missions" },
    { href: "/services/compte-rendu-chantier", label: "Comptes rendus chantier" },
    { href: "/services/doe-btp", label: "DOE BTP" },
    { href: "/ressources/pv-levee-reserves-btp", label: "PV levée de réserves" },
    { href: "/ressources/compte-rendu-chantier", label: "Guide compte rendu chantier" },
    { href: "/notre-facon-de-travailler", label: "Notre méthode BeWork" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Demander un échange" },
  ],
  "/assistant-travaux-france": [
    { href: "/assistant-travaux-paris", label: "Paris & Île-de-France" },
    { href: "/assistant-travaux-lyon", label: "Lyon" },
    { href: "/assistant-travaux-belgique", label: "Belgique" },
    { href: "/assistant-travaux-suisse", label: "Suisse" },
    { href: "/assistant-travaux-luxembourg", label: "Luxembourg" },
    { href: "/services/assistant-travaux", label: "Service assistant travaux" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres BTP" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-paris": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-lyon", label: "Lyon" },
    { href: "/assistant-travaux-marseille", label: "Marseille" },
    { href: "/reponse-appel-offres-btp", label: "Appels d'offres" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Contact" },
  ],
  "/assistant-travaux-belgique": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-suisse", label: "Suisse" },
    { href: "/assistant-travaux-luxembourg", label: "Luxembourg" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-suisse": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-belgique", label: "Belgique" },
    { href: "/assistant-travaux-luxembourg", label: "Luxembourg" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/assistant-travaux-luxembourg": [
    { href: "/assistant-travaux-france", label: "France" },
    { href: "/assistant-travaux-belgique", label: "Belgique" },
    { href: "/assistant-travaux-suisse", label: "Suisse" },
    { href: "/services/assistant-travaux", label: "Assistant travaux" },
    { href: "/tarifs", label: "Tarifs" },
  ],
  "/dict-dt-travaux": [
    { href: "/services/assistant-travaux", label: "Assistant travaux IA" },
    { href: "/ressources/ppsps-btp", label: "PPSPS BTP" },
    { href: "/admin-btp-sans-recruter", label: "Admin BTP sans recruter" },
  ],
  "/artisan-deborde-administratif": [
    { href: "/admin-btp-sans-recruter", label: "Admin BTP sans recruter" },
    { href: "/relance-devis-btp", label: "Relance devis" },
    { href: "/tarifs", label: "Tarifs" },
    { href: "/contact", label: "Démarrer un échange" },
  ],
  "/ressources/bework-maitrise-doeuvre": [
    { href: "/ressources/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/ressources/memoire-technique-btp", label: "Mémoire technique" },
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu chantier" },
    { href: "/ressources/doe-btp", label: "DOE BTP" },
    { href: "/tarifs", label: "Tarifs BeWork" },
  ],
  "/ressources/tuto-skill-planning-chantier-bework": [
    { href: "/ressources/planning-chantier-btp", label: "Guide planning chantier BTP" },
    { href: "/ressources/tuto-skill-constat-retard-bework", label: "Skill constat de retard" },
    { href: "/ressources/compte-rendu-chantier", label: "Compte rendu chantier" },
    { href: "/services/assistant-conducteur-de-travaux", label: "Assistant conducteur de travaux" },
    { href: "/chantier-mal-suivi", label: "Chantier mal suivi" },
  ],
  "/comparatif-assistance-travaux-btp": [
    { href: "/tarifs", label: "Tarifs BeWork" },
    { href: "/admin-btp-sans-recruter", label: "Sans recruter" },
    { href: "/assistants-administratifs-taches", label: "Catalogue missions" },
    { href: "/cas-clients", label: "Cas clients" },
    { href: "/contact", label: "Demander un échange" },
  ],
  "/checklist-depot-appel-offres-btp": [
    { href: "/blog/comment-repondre-appel-offres-btp", label: "Guide réponse AO" },
    { href: "/blog/eviter-rejet-offre-marche-public", label: "Éviter le rejet d'offre" },
    { href: "/reponse-appel-offres-btp", label: "Landing appels d'offres" },
    { href: "/services/analyse-dce-btp", label: "Analyse DCE" },
    { href: "/tarifs", label: "Tarifs" },
  ],
};

export function getSeoInternalLinks(path: string): SeoInternalLink[] {
  const exact = SEO_INTERNAL_LINKS[path];
  if (exact?.length) return exact;

  // Fallback cluster ressources (tutos / guides sans entrée dédiée).
  if (
    path.startsWith("/ressources/tuto-") ||
    path.startsWith("/ressources/guide-") ||
    (path.startsWith("/ressources/") && path !== "/ressources")
  ) {
    return [
      { href: "/ressources/tutos", label: "Tous les tutos skills" },
      { href: "/ressources", label: "Hub ressources BTP" },
      { href: "/services/assistant-travaux", label: "Assistant travaux BeWork" },
      { href: "/tarifs", label: "Tarifs" },
      { href: "/contact", label: "Contacter BeWork" },
    ];
  }

  return [];
}
