import type { DemoScenario } from "./types";

const F = true as const;

/** Scénario principal obligatoire — données 100 % fictives. */
export const SCENARIO_GO_LOGEMENTS: DemoScenario = {
  id: "go-logements-public",
  label: "Marché public — Gros œuvre — Logements collectifs",
  pitch: "Construction de 36 logements collectifs — Lot Gros œuvre",
  commercialAngle: "Montrer comment BeWork structure un marché dès la notification.",
  clientName: "Entreprise Démo Construction",
  worksiteTitle: "Construction de 36 logements collectifs — Lot Gros œuvre",
  location: "Zone fictive — Agglomération Démo (France)",
  lot: "Gros œuvre",
  marketType: "Marché public",
  amountHt: "1 850 000 € HT",
  healthLabel: "EN_DIFFICULTE",
  healthScore: 52,
  healthReasons: [
    "1 visa de fondation en retard",
    "1 TS sans validation écrite",
    "3 actions en retard",
  ],
  adminProgressPct: 58,
  doeProgressPct: 45,
  serviceLevel: "Pilotage Complet BeWork",
  actors: {
    conducteur: "Camille Durand (fictif)",
    assistant: "Léa Martin — BeWork (fictif)",
    moa: "Office fictif Habitat Démo",
    moe: "Atelier Architecture Démo",
    bc: "Contrôle Technique Démo",
    sps: "Coord. SPS Démo",
  },
  obligations: [
    { id: "o1", title: "Remettre le PPSPS avant démarrage", category: "Sécurité", priority: "Critique", status: "Validée", dueLabel: "J-15 démarrage", responsible: "Conducteur" },
    { id: "o2", title: "Transmettre le plan d’installation de chantier", category: "Méthodes", priority: "Haute", status: "Validée", dueLabel: "Avant installation", responsible: "Conducteur" },
    { id: "o3", title: "Remettre le planning détaillé d’exécution", category: "Planning", priority: "Haute", status: "En cours", dueLabel: "15/04/2026", responsible: "Conducteur" },
    { id: "o4", title: "Fournir les fiches techniques béton", category: "Technique", priority: "Haute", status: "En attente", dueLabel: "Avant 1er coulage", responsible: "Études" },
    { id: "o5", title: "Transmettre les plans de fondation", category: "Études", priority: "Critique", status: "En retard", dueLabel: "01/04/2026", responsible: "BE structure" },
    { id: "o6", title: "Transmettre les plans de coffrage", category: "Études", priority: "Haute", status: "À préparer", dueLabel: "20/04/2026", responsible: "BE structure" },
    { id: "o7", title: "Transmettre les plans de ferraillage", category: "Études", priority: "Haute", status: "À préparer", dueLabel: "25/04/2026", responsible: "BE structure" },
    { id: "o8", title: "Fournir les attestations des sous-traitants", category: "Administratif", priority: "Critique", status: "En cours", dueLabel: "Avant intervention ST", responsible: "Admin" },
    { id: "o9", title: "Remettre les contrôles de compactage", category: "Contrôles", priority: "Normale", status: "À préparer", dueLabel: "Fin terrassements", responsible: "Conducteur" },
    { id: "o10", title: "Constituer progressivement le DOE", category: "DOE", priority: "Haute", status: "En cours", dueLabel: "Continu", responsible: "Assistant BeWork" },
    { id: "o11", title: "Notifier le démarrage au coordonnateur SPS", category: "Sécurité", priority: "Haute", status: "Validée", dueLabel: "Avant installation", responsible: "Conducteur" },
    { id: "o12", title: "Transmettre le mémoire méthodologique fondations", category: "Méthodes", priority: "Normale", status: "Envoyée", dueLabel: "10/04/2026", responsible: "Études" },
    { id: "o13", title: "Fournir l’attestation décennale à jour", category: "Assurances", priority: "Critique", status: "Validée", dueLabel: "À la notification", responsible: "Admin" },
    { id: "o14", title: "Remettre le registre des sous-traitants agréés", category: "Administratif", priority: "Haute", status: "En cours", dueLabel: "Mensuel", responsible: "Admin" },
    { id: "o15", title: "Transmettre les PV de réception des armatures", category: "Contrôles", priority: "Normale", status: "À préparer", dueLabel: "Par phase", responsible: "Conducteur" },
    { id: "o16", title: "Communiquer le planning béton mensuel", category: "Planning", priority: "Normale", status: "En cours", dueLabel: "Mensuel", responsible: "Conducteur" },
    { id: "o17", title: "Remettre les fiches de poste / modes opératoires", category: "Sécurité", priority: "Haute", status: "Validée", dueLabel: "Avant installation", responsible: "SPS / Conducteur" },
    { id: "o18", title: "Archiver les OS et avenants dans le dossier marché", category: "Contractuel", priority: "Haute", status: "En cours", dueLabel: "Continu", responsible: "Assistant BeWork" },
  ],
  documents: [
    { id: "d1", name: "DOCUMENT FICTIF — PPSPS", category: "Sécurité", status: "Validé", mandatory: true, fictionMark: F },
    { id: "d2", name: "DOCUMENT FICTIF — Plan d’installation de chantier", category: "Méthodes", status: "Validé", mandatory: true, fictionMark: F },
    { id: "d3", name: "DOCUMENT FICTIF — Attestation d’assurance", category: "Administratif", status: "Validé", mandatory: true, fictionMark: F },
    { id: "d4", name: "DOCUMENT FICTIF — Fiche technique béton C30/37", category: "Technique", status: "À vérifier", mandatory: true, fictionMark: F },
    { id: "d5", name: "DOCUMENT FICTIF — Plan de fondation indice B", category: "Plans", status: "En attente de visa", mandatory: true, fictionMark: F },
    { id: "d6", name: "DOCUMENT FICTIF — Plan de coffrage RDC", category: "Plans", status: "À préparer", mandatory: true, fictionMark: F },
    { id: "d7", name: "DOCUMENT FICTIF — Plan de ferraillage", category: "Plans", status: "À préparer", mandatory: true, fictionMark: F },
    { id: "d8", name: "DOCUMENT FICTIF — Rapport de contrôle de compactage", category: "Contrôles", status: "Manquant", mandatory: true, fictionMark: F },
    { id: "d9", name: "DOCUMENT FICTIF — Bon de livraison béton", category: "Fournisseurs", status: "Manquant", mandatory: false, fictionMark: F },
    { id: "d10", name: "DOCUMENT FICTIF — Procès-verbal d’essai", category: "Contrôles", status: "Manquant", mandatory: true, fictionMark: F },
    { id: "d11", name: "DOCUMENT FICTIF — Plan de recollement", category: "DOE", status: "À demander", mandatory: true, fictionMark: F },
    { id: "d12", name: "DOCUMENT FICTIF — Attestation URSSAF ST ferraillage", category: "Sous-traitance", status: "À corriger", mandatory: true, fictionMark: F },
    { id: "d13", name: "DOCUMENT FICTIF — Planning d’exécution v2", category: "Planning", status: "Validé", mandatory: true, fictionMark: F },
    { id: "d14", name: "DOCUMENT FICTIF — OS de démarrage", category: "Contractuel", status: "Validé", mandatory: true, fictionMark: F },
  ],
  actions: [
    { id: "a1", title: "Relancer le bureau d’études pour le plan de fondation", category: "Visa", priority: "Critique", status: "En cours", dueLabel: "Hier", overdue: true },
    { id: "a2", title: "Faire valider la fiche technique béton", category: "Document", priority: "Haute", status: "En cours", dueLabel: "Aujourd’hui" },
    { id: "a3", title: "Demander l’attestation URSSAF du sous-traitant", category: "Sous-traitance", priority: "Haute", status: "En retard", dueLabel: "Il y a 3 j", overdue: true },
    { id: "a4", title: "Préparer la situation mensuelle n°3", category: "Situation", priority: "Normale", status: "À faire", dueLabel: "Cette semaine" },
    { id: "a5", title: "Vérifier le devis de travaux supplémentaires TS-02", category: "TS", priority: "Haute", status: "En attente maîtrise d’œuvre", dueLabel: "Cette semaine" },
    { id: "a6", title: "Compléter le DOE (fiches techniques)", category: "DOE", priority: "Normale", status: "En cours", dueLabel: "Continu" },
    { id: "a7", title: "Préparer le rapport hebdomadaire", category: "Rapport", priority: "Normale", status: "À faire", dueLabel: "Vendredi" },
    { id: "a8", title: "Relancer visa coffrage RDC", category: "Visa", priority: "Haute", status: "À faire", dueLabel: "Semaine prochaine" },
    { id: "a9", title: "Archiver BL béton fictifs de la semaine", category: "Document", priority: "Basse", status: "En retard", dueLabel: "Il y a 2 j", overdue: true },
  ],
  plans: [
    { id: "p1", reference: "FON-01", title: "Plans de fondation", indice: "B", status: "En attente de visa", visaDueLabel: "01/04/2026", overdue: true },
    { id: "p2", reference: "COF-RDC", title: "Coffrage rez-de-chaussée", indice: "A", status: "Envoyé pour visa", visaDueLabel: "20/04/2026" },
    { id: "p3", reference: "FER-01", title: "Ferraillage semelles", indice: "A", status: "À produire", visaDueLabel: "25/04/2026" },
    { id: "p4", reference: "PIC-01", title: "Plan d’installation de chantier", indice: "C", status: "Validé", visaDueLabel: "—" },
    { id: "p5", reference: "COF-R+1", title: "Coffrage R+1", indice: "—", status: "À produire", visaDueLabel: "À planifier" },
    { id: "p6", reference: "REC-01", title: "Plan de recollement (DOE)", indice: "—", status: "À produire", visaDueLabel: "Avant réception" },
  ],
  milestones: [
    { id: "m1", title: "Notification du marché", category: "Administratif", status: "Atteint", plannedLabel: "15/02/2026", sortOrder: 10 },
    { id: "m2", title: "Fin de la période de préparation", category: "Administratif", status: "Atteint", plannedLabel: "15/03/2026", sortOrder: 20 },
    { id: "m3", title: "Installation de chantier", category: "Sécurité", status: "Atteint", plannedLabel: "20/03/2026", sortOrder: 30 },
    { id: "m4", title: "Démarrage des fondations", category: "Travaux", status: "Bloqué", plannedLabel: "05/04/2026", sortOrder: 40 },
    { id: "m5", title: "Réception prévisionnelle", category: "Réception", status: "Non démarré", plannedLabel: "15/12/2026", sortOrder: 100 },
  ],
  blockers: [
    {
      id: "b1",
      title: "Plan de fondation non visé",
      severity: "Critique",
      consequence: "Empêche le démarrage sécurisé des fondations et expose à un retard de planning.",
      impactedMilestone: "Démarrage des fondations",
      internalOwner: "Camille Durand (fictif)",
      externalDecider: "BE structure / MOE (fictifs)",
      nextAction: "Relance formelle + proposition de réunion technique",
      daysOpen: 12,
      status: "Ouvert",
    },
    {
      id: "b2",
      title: "Travail supplémentaire sans validation écrite",
      severity: "Important",
      consequence: "Risque de non-paiement et de litige sur le périmètre.",
      impactedMilestone: "Suivi financier administratif",
      internalOwner: "Léa Martin — BeWork (fictif)",
      externalDecider: "Maître d’œuvre (fictif)",
      nextAction: "Obtenir validation écrite du devis TS-02 (18 400 € HT fictifs)",
      daysOpen: 5,
      status: "Ouvert",
    },
  ],
  subcontractors: [
    {
      id: "s1",
      companyName: "Ferraillage Démo SAS (fictif)",
      prestation: "Fourniture et pose armatures",
      approvalStatus: "Agréé",
      dossierStatus: "Incomplet",
    },
    {
      id: "s2",
      companyName: "Coffrage Services Démo (fictif)",
      prestation: "Location et mise en œuvre coffrage",
      approvalStatus: "En instruction",
      dossierStatus: "En cours",
    },
  ],
  situations: [
    { id: "si1", number: "SIT-01", periodLabel: "Mars 2026", requestedHt: "95 000", validatedHt: "92 500", paidHt: "92 500", status: "Payée" },
    { id: "si2", number: "SIT-02", periodLabel: "Avril 2026", requestedHt: "140 000", validatedHt: "132 000", paidHt: "—", status: "Validée" },
    { id: "si3", number: "SIT-03", periodLabel: "Mai 2026", requestedHt: "—", validatedHt: "—", paidHt: "—", status: "En préparation" },
  ],
  extraWorks: [
    {
      id: "ts1",
      reference: "TS-01",
      description: "Adaptation semelles suite observation géotechnique (fictif)",
      estimatedHt: "12 200",
      writtenValidation: true,
      startedWithoutValidation: false,
      status: "Validé",
    },
    {
      id: "ts2",
      reference: "TS-02",
      description: "Renforcement localisé suite modification architecture (fictif)",
      estimatedHt: "18 400",
      writtenValidation: false,
      startedWithoutValidation: true,
      status: "En attente validation",
    },
  ],
  doeItems: [
    { id: "doe1", title: "Plans de recollement", category: "Plans de recollement", status: "Manquant", mandatory: true },
    { id: "doe2", title: "Plans d’exécution visés", category: "Plans d’exécution validés", status: "À vérifier", mandatory: true },
    { id: "doe3", title: "Fiches techniques béton", category: "Fiches techniques", status: "À corriger", mandatory: true },
    { id: "doe4", title: "PV d’essais béton", category: "PV d’essais", status: "Manquant", mandatory: true },
    { id: "doe5", title: "Bons de livraison béton", category: "Documents fournisseurs", status: "Conforme", mandatory: false },
    { id: "doe6", title: "Attestations sous-traitants", category: "Documents sous-traitants", status: "À vérifier", mandatory: true },
    { id: "doe7", title: "PPSPS et avenants sécurité", category: "Sécurité", status: "Conforme", mandatory: true },
    { id: "doe8", title: "Notices d’entretien structure", category: "Notices", status: "Manquant", mandatory: true },
  ],
  report: {
    id: "r1",
    title: "Synthèse hebdomadaire de pilotage (DOCUMENT FICTIF)",
    periodLabel: "Semaine du 31 mars 2026",
    summary: [
      "3 actions clôturées, 9 actions ouvertes dont 3 en retard.",
      "Blocage critique : visa fondation — jalon fondations bloqué.",
      "TS-02 sans validation écrite — relance MOE en cours.",
      "DOE à 45 % — priorité fiches techniques et PV d’essais.",
      "Prochaine échéance critique : validation visa FON-01.",
    ],
  },
};
